<?php
/** ---------------------------------------------------------------------
 * app/lib/Exit/BaseExitFormat.php :
 * ----------------------------------------------------------------------
 * CollectiveAccess
 * Open-source collections management software
 * ----------------------------------------------------------------------
 *
 * Software by Whirl-i-Gig (http://www.whirl-i-gig.com)
 * Copyright 2025 Whirl-i-Gig
 *
 * For more information visit http://www.CollectiveAccess.org
 *
 * This program is free software; you may redistribute it and/or modify it under
 * the terms of the provided license as published by Whirl-i-Gig
 *
 * CollectiveAccess is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTIES whatsoever, including any implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * This source code is free and modifiable under the terms of
 * GNU General Public License. (http://www.gnu.org/copyleft/gpl.html). See
 * the "license.txt" file for details, or visit the CollectiveAccess web site at
 * http://www.CollectiveAccess.org
 *
 * @package CollectiveAccess
 * @subpackage Exit
 * @license http://www.gnu.org/copyleft/gpl.html GNU Public License version 3
 *
 * ----------------------------------------------------------------------
 */
namespace Exit\Formats;

abstract class BaseExitFormat {
	# -------------------------------------------------------
	static $s_format_settings = [];
	# -------------------------------------------------------
	protected $name = null;
	protected $log = null;
	# -------------------------------------------------------
	public function __construct(){

	}
	# -------------------------------------------------------
	public function getFormatSettings() {
		return BaseExitFormat::$s_format_settings[$this->getName()];
	}
	# -------------------------------------------------------
	public function getName() {
		return $this->name;
	}
	# -------------------------------------------------------
	public function setLogger(KLogger $logger) {
		$this->log = $logger;
	}
	# -------------------------------------------------------
	/**
	 * Log given message on level debug if logger is available (must be set via setLogger()).
	 * All export format messages are debug level because there's usually nothing interesting going on.
	 * @param string $message log message
	 */
	protected function log(string $message) {
		if($this->log && ($this->log instanceof KLogger)) {
			$this->log->logDebug($message);
		}
	}
	# -------------------------------------------------------
	/**
	 * Converts array version of item-level export generated by ca_data_exporters string version of the implemented format.
	 * For more info on the format @see ca_data_exporters::processExporterItem()
	 * @param array $pa_data export data
	 * @param array $pa_options option array
	 *  singleRecord = Gives a signal to the export format implementation that this is a single record export. For certain formats
	 * 		this might trigger different behavior, for instance the XML export format prepends the item-level output with <?xml ... ?>
	 * 		in those cases
	 * 	options = array of exporter options
	 * @return string export
	 */
	abstract public function processExport(array $data,?array $options=[]);
	# -------------------------------------------------------
	abstract public function getFileExtension(array $settings);
	# -------------------------------------------------------
	abstract public function getContentType(array $setting);
	# -------------------------------------------------------
}
