# Javascript manager configuration

asset_suffix = <ca_release_type>_<ca_version>

packages = {
	
	# -----------------------
}

loadSets = {
	#
	# Libraries listed in "_default" are always loaded (whether or not they have been
	# registered in code to load), are loaded in the order listed and are always 
	# loaded first
	#
	_default = [
		 
	],
	
}
