crate_types = [crate]
packing_statuses = {
	assigned = {
		relationship_type = assigned
	},
	packed = {
		relationship_type = packed
	},
	previous = {
		relationship_type = previous
	}	
}

crate_pack_date_element_code = date_packed
crate_unpack_date_element_code = date_unpacked