#
# Crate management options#
#
# Specific types of objects may be designated as crates - objects 
# meant to contain other objects during shipping. Crates have relationships
# to the objects that they may contain, do contain or have contained, as well
# as a date field for recording packing and unpack dates
#
# These options are only relevant if you are one of the handful of museums in 
# the world that insists on treating packing boxes as full-fledged objects to be 
# managed. If you are not one of these than there's nothing to see here.
# 

# Object types to be treated as crates
crate_types = []

# Association of object-object relationship types with packing statuses between collection
# objects and crates. Related collection items may have any or all of the following statuses:
#
#		"assigned" = Crate is the assigned packaging for the collection item
#		"packed" = Collection item is currently packed in crate. 
#					Date of packing is set in an object-object interstitial date element specified 
#					in the "crate_pack_date_element_code" setting below.
#		"previous" = Collection item was previously packed in crate. 
#					Dates of packing and unpacking are set in an object-object interstitial date 
#					element specified in the "crate_pack_date_element_code" and 
#					"crate_unpack_date_element_code" settings below.
packing_statuses = {
	assigned = {
		relationship_type = assigned
	},
	packed = {
		relationship_type = packed
	},
	previous = {
		relationship_type = previous
	}	
}

# Interstitial metadata element on object-object relationship recording date of packing
crate_pack_date_element_code = date_packed

# Interstitial metadata element on object-object relationship recording date of unpacking
crate_unpack_date_element_code = date_unpacked